# Agenda
* Numpy
* Pandas
* Lab


# Introduction


## Create a new notebook for your code-along:

From our submission directory, type:
    
    jupyter notebook

From the IPython Dashboard, open a new notebook.
Change the title to: "Numpy and Pandas"

# Introduction to Numpy

* Overview
* ndarray
* Indexing and Slicing

More info: [http://wiki.scipy.org/Tentative_NumPy_Tutorial](http://wiki.scipy.org/Tentative_NumPy_Tutorial)


## Numpy Overview

* Why Python for Data? Numpy brings *decades* of C math into Python!
* Numpy provides a wrapper for extensive C/C++/Fortran codebases, used for data analysis functionality
* NDAarray allows easy vectorized math and broadcasting (i.e. functions for vector elements of different shapes)

In [2]:
import numpy as np

### Creating ndarrays

In [3]:
# import function #from pn import 

An array object represents a multidimensional, homogeneous array of fixed-size items. 

In [4]:
# Creating arrays
a = np.zeros((3))
b = np.ones((2,3))
c = np.random.randint(1,10,(2,3,4))
d = np.arange(0,11,1)

What are these functions?

    arange?

In [5]:
# Note the way each array is printed:
a,b,c,d

(array([ 0.,  0.,  0.]), array([[ 1.,  1.,  1.],
        [ 1.,  1.,  1.]]), array([[[1, 2, 7, 6],
         [5, 8, 4, 9],
         [1, 1, 5, 2]],
 
        [[3, 1, 9, 5],
         [8, 5, 9, 1],
         [9, 6, 5, 9]]]), array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [6]:
## Arithmetic in arrays is element wise

In [7]:
a = np.array( [20,30,40,50] )
b = np.arange( 4 )
b

array([0, 1, 2, 3])

In [8]:
c = a-b
c

array([20, 29, 38, 47])

In [9]:
b**2

array([0, 1, 4, 9])

## Indexing, Slicing and Iterating

In [10]:
# one-dimensional arrays work like lists:
a = np.arange(10)**2

In [11]:
a

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [12]:
a[2:5]

array([ 4,  9, 16])

In [13]:
# Multidimensional arrays use tuples with commas for indexing
# with (row,column) conventions beginning, as always in Python, from 0

In [14]:
b = np.random.randint(1,100,(4,4))

In [15]:
?np.random.randint
b

array([[90, 59, 72, 30],
       [17, 91, 87, 91],
       [73, 83, 46, 95],
       [77, 96, 14, 14]])

In [16]:
# Guess the output
print(b[2,3])
print(b[0,0])


95
90


In [17]:
b[0:3,1],b[:,1]

(array([59, 91, 83]), array([59, 91, 83, 96]))

In [18]:
b[1:3,:]

array([[17, 91, 87, 91],
       [73, 83, 46, 95]])

# Introduction to Pandas

* Object Creation
* Viewing data
* Selection
* Missing data
* Grouping
* Reshaping
* Time series
* Plotting
* i/o
 

_pandas.pydata.org_

## Pandas Overview

_Source: [pandas.pydata.org](http://pandas.pydata.org/pandas-docs/stable/10min.html)_

In [19]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [106]:
dates = pd.date_range('20140101',periods=6)
# period refers to days
dates

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [107]:
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
z = pd.DataFrame(index = df.index, columns = df.columns)
df.columns
# 6 rows and 4 columns 

Index([u'A', u'B', u'C', u'D'], dtype='object')

In [108]:
# Index, columns, underlying numpy data
df.T
# transpose 
df

A         B         C         D
2014-01-01  0.935300 -0.662939  0.698485 -0.427597
2014-01-02 -1.932235 -0.708353 -0.040704  1.469581
2014-01-03  0.990729  0.831242  1.328825  0.635397
2014-01-04 -0.490685  0.043171 -1.325306 -0.327362
2014-01-05  0.884263  0.270903  0.364344  0.601174
2014-01-06  2.704273  0.831308  0.263266 -0.376974

In [109]:
df2 = pd.DataFrame({ 'A' : 1.,
                         'B' : pd.Timestamp('20130102'),
                         'C' : pd.Series(1,index=list(range(4)),dtype='float32'),
                         'D' : np.array([3] * 4,dtype='int32'),
                         'E' : 'foo' })
    

df2

A          B    C  D    E
0  1.0 2013-01-02  1.0  3  foo
1  1.0 2013-01-02  1.0  3  foo
2  1.0 2013-01-02  1.0  3  foo
3  1.0 2013-01-02  1.0  3  foo

In [110]:
# With specific dtypes
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E            object
dtype: object

#### Viewing Data

In [111]:
df.head()

A         B         C         D
2014-01-01  0.935300 -0.662939  0.698485 -0.427597
2014-01-02 -1.932235 -0.708353 -0.040704  1.469581
2014-01-03  0.990729  0.831242  1.328825  0.635397
2014-01-04 -0.490685  0.043171 -1.325306 -0.327362
2014-01-05  0.884263  0.270903  0.364344  0.601174

In [102]:
df.tail()

A          B          C         D
2014-01-01 00:01:35   9.624391 -11.429015  13.292026 -6.292710
2014-01-01 00:01:36   8.030926 -11.900635  12.696487 -6.191431
2014-01-01 00:01:37   9.546087 -12.688524  13.555538 -6.913254
2014-01-01 00:01:38  10.733033 -12.681388  14.214050 -8.534133
2014-01-01 00:01:39  11.464374 -13.644703  14.890931 -8.114304

In [27]:
df.index

DatetimeIndex(['2014-01-01', '2014-01-02', '2014-01-03', '2014-01-04',
               '2014-01-05', '2014-01-06'],
              dtype='datetime64[ns]', freq='D')

In [28]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.564743 -0.152849 -0.514315 -0.451736
std    0.847788  0.866554  1.321107  0.977144
min   -0.790244 -1.771080 -2.099192 -1.592978
25%    0.251080 -0.271543 -1.590078 -1.046723
50%    0.585260  0.056585 -0.486904 -0.456391
75%    1.060487  0.404710  0.529506 -0.252284
max    1.649599  0.600982  1.076606  1.223094

In [29]:
df.sort_values(by='B',inplace = True)

### Selection

In [101]:
df[['A','B']]
df.head()

A         B         C         D
2014-01-01 00:00:00 -1.233928  0.415302 -0.114150  0.133063
2014-01-01 00:00:01 -1.188406 -1.182822 -1.145366 -0.288239
2014-01-01 00:00:02 -0.597277 -1.126898 -1.679939  0.886342
2014-01-01 00:00:03 -0.506361  0.048457 -2.110157  1.146420
2014-01-01 00:00:04 -0.018356  0.079135 -1.612506  1.453023

In [86]:
df[0:3]

A         B         C         D
2014-01-01 00:00:00 -1.233928  0.415302 -0.114150  0.133063
2014-01-01 00:00:01 -1.188406 -1.182822 -1.145366 -0.288239
2014-01-01 00:00:02 -0.597277 -1.126898 -1.679939  0.886342

In [87]:
# By label
df.loc[dates[0]]

A   -1.233928
B    0.415302
C   -0.114150
D    0.133063
Name: 2014-01-01 00:00:00, dtype: float64

In [112]:
# multi-axis by label
df.loc[:,['A','B']]

A         B
2014-01-01  0.935300 -0.662939
2014-01-02 -1.932235 -0.708353
2014-01-03  0.990729  0.831242
2014-01-04 -0.490685  0.043171
2014-01-05  0.884263  0.270903
2014-01-06  2.704273  0.831308

In [113]:
# Date Range
df.loc['20140102':'20140104',['B']]

B
2014-01-02 -0.708353
2014-01-03  0.831242
2014-01-04  0.043171

In [115]:
# Fast access to scalar
df.at[dates[1],'B']

-0.70835276050416496

In [116]:
# iloc provides integer locations similar to np style
df.iloc[3:]

A         B         C         D
2014-01-04 -0.490685  0.043171 -1.325306 -0.327362
2014-01-05  0.884263  0.270903  0.364344  0.601174
2014-01-06  2.704273  0.831308  0.263266 -0.376974

### Boolean Indexing

In [117]:
df[df.A < 0] # Basically a 'where' operation

A         B         C         D
2014-01-02 -1.932235 -0.708353 -0.040704  1.469581
2014-01-04 -0.490685  0.043171 -1.325306 -0.327362

### Setting

In [121]:
df_posA = df.copy() # Without "copy" it would act on the dataset

df_posA[df_posA.A < 0] = -1*df_posA

In [122]:
df_posA

A         B         C         D
2014-01-01  0.935300 -0.662939  0.698485 -0.427597
2014-01-02  1.932235  0.708353  0.040704 -1.469581
2014-01-03  0.990729  0.831242  1.328825  0.635397
2014-01-04  0.490685 -0.043171  1.325306  0.327362
2014-01-05  0.884263  0.270903  0.364344  0.601174
2014-01-06  2.704273  0.831308  0.263266 -0.376974

In [125]:
#Setting new column aligns data by index
s1 = pd.Series([1,2,3,4,5,6],index=pd.date_range('20140102',periods=6))

In [126]:
s1

2014-01-02    1
2014-01-03    2
2014-01-04    3
2014-01-05    4
2014-01-06    5
2014-01-07    6
Freq: D, dtype: int64

In [127]:
df['F'] = s1

In [128]:
df

A         B         C         D    F
2014-01-01  0.935300 -0.662939  0.698485 -0.427597  NaN
2014-01-02 -1.932235 -0.708353 -0.040704  1.469581  1.0
2014-01-03  0.990729  0.831242  1.328825  0.635397  2.0
2014-01-04 -0.490685  0.043171 -1.325306 -0.327362  3.0
2014-01-05  0.884263  0.270903  0.364344  0.601174  4.0
2014-01-06  2.704273  0.831308  0.263266 -0.376974  5.0

### Missing Data

In [129]:
# Add a column with missing data
df1 = df.reindex(index=dates[0:4],columns=list(df.columns) + ['E'])
df1

A         B         C         D    F   E
2014-01-01  0.935300 -0.662939  0.698485 -0.427597  NaN NaN
2014-01-02 -1.932235 -0.708353 -0.040704  1.469581  1.0 NaN
2014-01-03  0.990729  0.831242  1.328825  0.635397  2.0 NaN
2014-01-04 -0.490685  0.043171 -1.325306 -0.327362  3.0 NaN

In [130]:
df1.loc[dates[0]:dates[1],'E'] = 1

In [131]:
df1

A         B         C         D    F    E
2014-01-01  0.935300 -0.662939  0.698485 -0.427597  NaN  1.0
2014-01-02 -1.932235 -0.708353 -0.040704  1.469581  1.0  1.0
2014-01-03  0.990729  0.831242  1.328825  0.635397  2.0  NaN
2014-01-04 -0.490685  0.043171 -1.325306 -0.327362  3.0  NaN

In [132]:
# find where values are null
pd.isnull(df1)

A      B      C      D      F      E
2014-01-01  False  False  False  False   True  False
2014-01-02  False  False  False  False  False  False
2014-01-03  False  False  False  False  False   True
2014-01-04  False  False  False  False  False   True

### Operations

In [133]:
df.describe()

A         B         C         D         F
count  6.000000  6.000000  6.000000  6.000000  5.000000
mean   0.515274  0.100889  0.214818  0.262370  3.000000
std    1.570516  0.683735  0.887347  0.767319  1.581139
min   -1.932235 -0.708353 -1.325306 -0.427597  1.000000
25%   -0.146948 -0.486411  0.035289 -0.364571  2.000000
50%    0.909781  0.157037  0.313805  0.136906  3.000000
75%    0.976872  0.691157  0.614950  0.626841  4.000000
max    2.704273  0.831308  1.328825  1.469581  5.000000

In [134]:
df.mean(),df.mean(1) # Operation on two different axes

(A    0.515274
 B    0.100889
 C    0.214818
 D    0.262370
 F    3.000000
 dtype: float64, 2014-01-01    0.135812
 2014-01-02   -0.042342
 2014-01-03    1.157239
 2014-01-04    0.179964
 2014-01-05    1.224137
 2014-01-06    1.684375
 Freq: D, dtype: float64)

### Applying functions

In [135]:
df

A         B         C         D    F
2014-01-01  0.935300 -0.662939  0.698485 -0.427597  NaN
2014-01-02 -1.932235 -0.708353 -0.040704  1.469581  1.0
2014-01-03  0.990729  0.831242  1.328825  0.635397  2.0
2014-01-04 -0.490685  0.043171 -1.325306 -0.327362  3.0
2014-01-05  0.884263  0.270903  0.364344  0.601174  4.0
2014-01-06  2.704273  0.831308  0.263266 -0.376974  5.0

In [136]:
df.apply(np.cumsum)

A         B         C         D     F
2014-01-01  0.935300 -0.662939  0.698485 -0.427597   NaN
2014-01-02 -0.996936 -1.371292  0.657781  1.041984   1.0
2014-01-03 -0.006206 -0.540050  1.986606  1.677381   3.0
2014-01-04 -0.496891 -0.496878  0.661300  1.350019   6.0
2014-01-05  0.387371 -0.225976  1.025644  1.951193  10.0
2014-01-06  3.091644  0.605333  1.288910  1.574219  15.0

In [137]:
df.apply(lambda x: x.max() - x.min())

A    4.636508
B    1.539661
C    2.654131
D    1.897178
F    4.000000
dtype: float64

In [53]:
# Built in string methods
s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

### Merge

In [54]:
np.random.randn(10,4)

array([[ 0.55153012,  2.10291655, -0.33608272, -0.58671395],
       [ 1.0830964 ,  0.05296425,  0.76690518, -0.5306428 ],
       [ 1.28529099, -0.75761886, -1.18454254, -0.7656241 ],
       [-1.00799385,  0.22507445,  0.00370981,  0.77579125],
       [ 1.73124269,  1.30383926, -0.77588896,  0.538183  ],
       [ 0.25077156,  0.88806185, -1.04708803,  3.23182399],
       [ 0.78111804,  0.16116325,  0.12179383, -1.0445436 ],
       [-0.8239312 ,  0.56405345,  0.46309661,  0.70840239],
       [ 0.18924439, -0.32483938, -0.80824331,  0.4660286 ],
       [ 0.14162676,  0.32846145,  0.71810309, -1.33847208]])

In [55]:
#Concatenating pandas objects together
df = pd.DataFrame(np.random.randn(10,4))
df

0         1         2         3
0 -0.897897 -0.285934 -0.534788 -0.274964
1 -0.697926  0.865614 -1.735800  1.176719
2  0.280658  1.926370  0.563666  0.426085
3 -0.827723 -0.408316 -1.060363 -0.341402
4 -0.434929 -0.330303 -0.819767 -2.269719
5 -1.350179  1.691937 -0.071000  0.296833
6  0.022538  1.070783  0.089709 -0.261461
7 -0.999078 -1.402756 -0.488364 -0.559861
8  0.269104  1.455479 -0.134282 -0.553489
9 -2.003964  1.069025  0.776262  0.063078

In [56]:
# Break it into pieces
pieces = [df[:3], df[3:7],df[7:]]
pieces

[          0         1         2         3
 0 -0.897897 -0.285934 -0.534788 -0.274964
 1 -0.697926  0.865614 -1.735800  1.176719
 2  0.280658  1.926370  0.563666  0.426085,
           0         1         2         3
 3 -0.827723 -0.408316 -1.060363 -0.341402
 4 -0.434929 -0.330303 -0.819767 -2.269719
 5 -1.350179  1.691937 -0.071000  0.296833
 6  0.022538  1.070783  0.089709 -0.261461,
           0         1         2         3
 7 -0.999078 -1.402756 -0.488364 -0.559861
 8  0.269104  1.455479 -0.134282 -0.553489
 9 -2.003964  1.069025  0.776262  0.063078]

In [57]:
pd.concat(pieces)

0         1         2         3
0 -0.897897 -0.285934 -0.534788 -0.274964
1 -0.697926  0.865614 -1.735800  1.176719
2  0.280658  1.926370  0.563666  0.426085
3 -0.827723 -0.408316 -1.060363 -0.341402
4 -0.434929 -0.330303 -0.819767 -2.269719
5 -1.350179  1.691937 -0.071000  0.296833
6  0.022538  1.070783  0.089709 -0.261461
7 -0.999078 -1.402756 -0.488364 -0.559861
8  0.269104  1.455479 -0.134282 -0.553489
9 -2.003964  1.069025  0.776262  0.063078

In [58]:
# Also can "Join" and "Append"
df

0         1         2         3
0 -0.897897 -0.285934 -0.534788 -0.274964
1 -0.697926  0.865614 -1.735800  1.176719
2  0.280658  1.926370  0.563666  0.426085
3 -0.827723 -0.408316 -1.060363 -0.341402
4 -0.434929 -0.330303 -0.819767 -2.269719
5 -1.350179  1.691937 -0.071000  0.296833
6  0.022538  1.070783  0.089709 -0.261461
7 -0.999078 -1.402756 -0.488364 -0.559861
8  0.269104  1.455479 -0.134282 -0.553489
9 -2.003964  1.069025  0.776262  0.063078

### Grouping


In [59]:
df = pd.DataFrame({'A' : ['foo', 'bar', 'foo', 'bar',
                       'foo', 'bar', 'foo', 'foo'],
                       'B' : ['one', 'one', 'two', 'three',
                             'two', 'two', 'one', 'three'],
                       'C' : np.random.randn(8),
                       'D' : np.random.randn(8)})

In [60]:
df

A      B         C         D
0  foo    one -0.454191 -0.698638
1  bar    one -0.241044  0.528498
2  foo    two  1.298422  0.289554
3  bar  three -0.572012 -1.688775
4  foo    two  0.558286 -1.064222
5  bar    two -0.480178 -0.143985
6  foo    one -1.546461 -0.485287
7  foo  three  1.249940  0.977177

In [61]:
df.groupby(['A','B']).sum()

C         D
A   B                        
bar one   -0.241044  0.528498
    three -0.572012 -1.688775
    two   -0.480178 -0.143985
foo one   -2.000652 -1.183925
    three  1.249940  0.977177
    two    1.856708 -0.774668

### Reshaping

In [62]:
# You can also stack or unstack levels

In [63]:
a = df.groupby(['A','B']).sum()

In [64]:
# Pivot Tables
pd.pivot_table(df,values=['C','D'],index=['A'],columns=['B'])

C                             D                    
B         one     three       two       one     three       two
A                                                              
bar -0.241044 -0.572012 -0.480178  0.528498 -1.688775 -0.143985
foo -1.000326  1.249940  0.928354 -0.591963  0.977177 -0.387334

### Time Series


In [65]:
import pandas as pd
import numpy as np

In [66]:
# 100 Seconds starting on January 1st
rng = pd.date_range('1/1/2014', periods=100, freq='S')

In [67]:
# Give each second a random value
ts = pd.Series(np.random.randint(0, 500, len(rng)), index=rng)

In [69]:
ts

2014-01-01 00:00:00    381
2014-01-01 00:00:01    485
2014-01-01 00:00:02    182
2014-01-01 00:00:03    431
2014-01-01 00:00:04    235
2014-01-01 00:00:05    314
2014-01-01 00:00:06      9
2014-01-01 00:00:07    256
2014-01-01 00:00:08    361
2014-01-01 00:00:09     70
2014-01-01 00:00:10    189
2014-01-01 00:00:11    290
2014-01-01 00:00:12    116
2014-01-01 00:00:13    488
2014-01-01 00:00:14    345
2014-01-01 00:00:15      8
2014-01-01 00:00:16    139
2014-01-01 00:00:17    111
2014-01-01 00:00:18     88
2014-01-01 00:00:19    215
2014-01-01 00:00:20    400
2014-01-01 00:00:21    134
2014-01-01 00:00:22    392
2014-01-01 00:00:23      8
2014-01-01 00:00:24    379
2014-01-01 00:00:25    446
2014-01-01 00:00:26    302
2014-01-01 00:00:27    399
2014-01-01 00:00:28    105
2014-01-01 00:00:29    324
                      ... 
2014-01-01 00:01:10    428
2014-01-01 00:01:11     93
2014-01-01 00:01:12    102
2014-01-01 00:01:13    498
2014-01-01 00:01:14    317
2014-01-01 00:01:15    122
2

In [70]:
# Built in resampling
ts.resample('1Min').mean() # Resample secondly to 1Minutely

2014-01-01 00:00:00    255.066667
2014-01-01 00:01:00    246.425000
Freq: T, dtype: float64

In [71]:
# Many additional time series features
ts. #use tab

SyntaxError: invalid syntax (<ipython-input-71-5c9240a56f62>, line 2)

### Plotting


In [72]:
ts.plot()

In [73]:
def randwalk(startdate,points):
    ts = pd.Series(np.random.randn(points), index=pd.date_range(startdate, periods=points))
    ts=ts.cumsum()
    ts.plot()
    return(ts)

In [74]:
# Using pandas to make a simple random walker by repeatedly running:
a=randwalk('1/1/2012',1000)

In [75]:
# Pandas plot function will print with labels as default

In [76]:
df = pd.DataFrame(np.random.randn(100, 4), index=ts.index,columns=['A', 'B', 'C', 'D'])
df = df.cumsum()
plt.figure();df.plot();plt.legend(loc='best') #

### I/O
I/O is straightforward with, for example, pd.read_csv or df.to_csv

#### The benefits of open source:

Let's look under x's in plt modules

# Next Steps

**Recommended Resources**

Name | Description
--- | ---
[Official Pandas Tutorials](http://pandas.pydata.org/pandas-docs/stable/10min.html) | Wes & Company's selection of tutorials and lectures
[Julia Evans Pandas Cookbook](https://github.com/jvns/pandas-cookbook) | Great resource with examples from weather, bikes and 311 calls
[Learn Pandas Tutorials](https://bitbucket.org/hrojas/learn-pandas) | A great series of Pandas tutorials from Dave Rojas
[Research Computing Python Data PYNBs](https://github.com/ResearchComputing/Meetup-Fall-2013/tree/master/python) | A super awesome set of python notebooks from a meetup-based course exclusively devoted to pandas